//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Agent
    {
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string AgentCode { get; set; }
        public string OperatorID { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<byte> InActive { get; set; }
        public string OperatorSubID { get; set; }
    }
}
