//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Setting
    {
        public int SettingID { get; set; }
        public string SettingCode { get; set; }
        public string SettingVal { get; set; }
    }
}
