//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSSysEntities : DbContext
    {
        public SMSSysEntities()
            : base("name=SMSSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Agent> M_Agent { get; set; }
        public virtual DbSet<M_Draw> M_Draw { get; set; }
        public virtual DbSet<M_Operator> M_Operator { get; set; }
        public virtual DbSet<M_OperatorSub> M_OperatorSub { get; set; }
        public virtual DbSet<M_Sim> M_Sim { get; set; }
        public virtual DbSet<T_DrawResult> T_DrawResult { get; set; }
        public virtual DbSet<T_MsgReply> T_MsgReply { get; set; }
        public virtual DbSet<T_MsgReplySent> T_MsgReplySent { get; set; }
        public virtual DbSet<T_OperatorCr> T_OperatorCr { get; set; }
        public virtual DbSet<T_OperatorDr> T_OperatorDr { get; set; }
        public virtual DbSet<T_ReceivedBet> T_ReceivedBet { get; set; }
        public virtual DbSet<T_ReceivedBetArc> T_ReceivedBetArc { get; set; }
        public virtual DbSet<T_SentSMS_ForDel> T_SentSMS_ForDel { get; set; }
        public virtual DbSet<T_SMSNotif> T_SMSNotif { get; set; }
        public virtual DbSet<M_Setting> M_Setting { get; set; }
        public virtual DbSet<viewActiveOperatorAgent> viewActiveOperatorAgents { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<M_Users> M_Users { get; set; }
    }
}
