//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OperatorDr
    {
        public string OperatorDrID { get; set; }
        public string OperatorID { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<System.DateTime> DrawDate { get; set; }
        public string DrawTime { get; set; }
        public Nullable<long> DrawPeriod { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string DrDesc { get; set; }
    }
}
