//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReceivedBet
    {
        public string ReceivedBetID { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedFrom { get; set; }
        public Nullable<long> FromMobile { get; set; }
        public string CombinationNo { get; set; }
        public Nullable<int> StraightAmtBet { get; set; }
        public Nullable<int> RambolAmtBet { get; set; }
        public string ForDraw { get; set; }
        public Nullable<decimal> WonAmtStr { get; set; }
        public Nullable<decimal> WonAmtRam { get; set; }
        public Nullable<long> OperatorMobile { get; set; }
        public string OperatorName { get; set; }
        public string OperatorCode { get; set; }
        public string AgentName { get; set; }
        public Nullable<bool> isAgent { get; set; }
        public string DrawResult { get; set; }
    }
}
