//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SentSMS_ForDel
    {
        public string SentSMSID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string SentTo { get; set; }
        public Nullable<int> SentMobile { get; set; }
        public string SMSMsg { get; set; }
        public string ReceivedBetID { get; set; }
        public string SentBy_EmpName { get; set; }
        public string SentBy_SimID { get; set; }
    }
}
