//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SMSNotif
    {
        public string NotifID { get; set; }
        public string OperatorCode { get; set; }
        public string DrawTime { get; set; }
        public string DrawDate { get; set; }
    }
}
