//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSTLDevEx.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewActiveOperatorAgent
    {
        public string AgentName { get; set; }
        public string AgentID { get; set; }
        public Nullable<long> OperatorMobile { get; set; }
        public string OperatorName { get; set; }
        public string OperatorCode { get; set; }
        public Nullable<long> MobileNo { get; set; }
    }
}
